### ISSUE TITLE
Load the 6to5 polyfill in helper fn for tests.

### ISSUE THREAD

**Issue by jmeas** [jmeas/es6-library-boilerplate#25]

**Comment by jmeas** [comment]
I'm going to close this for now. This duplication only happens when running the browser tests, and it's a pretty small runtime. Which is good because I also can't figure out exactly how to make the change from the docs. Maybe @thejameskyle could explain if he had a moment

**Comment by thejameskyle** [comment]
What duplication?

**Comment by jmeas** [comment]
I compile the files individually before bundling w. browserify. I imagine that 6to5 adds the runtime to each of those individual files? I'm just inferring this from the docs
