### ISSUE TITLE
Module Formatter instead of wrapper file

### ISSUE THREAD

**Issue by thejameskyle** [jmeas/es6-library-boilerplate#30]
You could extend 6to5's built-in [`UMDFormatter`](https://github.com/6to5/6to5/blob/master/lib/6to5/transformation/modules/umd.js) and add globals yourself if you want.

```json
// config.json
{
  "exports": "globalName",
  "imports": {
    "lodash": "_"
  }
}
```

```js
// library-formatter.js
import util from 'util';
import config from '../config.json';

export default class extends UMDFormatter() {
  transform(ast) {
    // transform ast...
  }
}
```

Then open source it!

**Comment by jmeas** [comment]
Oh really? That is awesome. I'll look into this. Thanks @thejameskyle!

**Comment by jmeas** [comment]
This seems like a lot of work, and esperanto supports umd outta tha box. Gonna close in favor of setting that up. Ref #47
