### ISSUE TITLE
Integrate w. code climate and add badges to docs

### ISSUE THREAD

**Issue by jmeas** [jmeas/es6-library-boilerplate#37]

**Comment by jmeas** [comment]
Istanbul uses esprima which only has [partial support for ES6](http://esprima.org/doc/es6.html), so that's out of the question for coverage.

**Comment by jmeas** [comment]
^ nvm. I can compile to commonjs and instrument that.

**Comment by jmeas** [comment]
I should have guessed it – @thejameskyle has [the solution](https://github.com/marionette-wires/wires-namespace/blob/master/package.json#L28) :)

**Comment by thejameskyle** [comment]
:stuck_out_tongue_winking_eye:

**Comment by jmeas** [comment]
Instead of coveralls, I'm going to use CodeClimate. CodeClimate gives you coverage and also some extra stats if you're interested in that sorta thing.
