### ISSUE TITLE
Update 6to5 to v3

### ISSUE THREAD

**Issue by jmeas** [jmeas/es6-library-boilerplate#53]
May depend on #47 'cause the new 6to5 doesn't let me `import` or `export` inside of the wrapper, ~~unless @thejameskyle knows some clever way to get around that?~~

**Update:** Ah, loose mode lets you get around it!

**Comment by thejameskyle** [comment]
I'm not sure defaulting to loose mode is all that great of an idea

**Comment by jmeas** [comment]
It's only loose mode for modules tho'. That's fine, right?

**Comment by jmeas** [comment]
Also once #47 lands, I can get rid of the loosemode.

**Comment by thejameskyle** [comment]
Ah, I didn't look at the actual setting. That's fine
