### ISSUE TITLE
Change LICENSE from MIT to ISC 

### ISSUE THREAD

**Issue by thejameskyle** [jmeas/es6-library-boilerplate#72]
ISC replaces MIT as being the most modern license for open source, it's now the default for npm packages.

**Comment by jmeas** [comment]
Going to close, 'cause I don't think there's any functional difference between the two. If you can post a convincing blog post/article/Github issue that gives a strong reason to use ISC over MIT, then I'll update the license. Otherwise, it just seems like a change for the sake of change.
